# Generated by Django 2.2.2 on 2019-07-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190701_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.CharField(max_length=200)),
                ('time_submitted', models.DateTimeField(verbose_name='time_submitted')),
                ('calculated_prediction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Prediction')),
                ('choices', models.ManyToManyField(to='quiz.Choice')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
    ]
