# Generated by Django 2.2.2 on 2019-07-12 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_submit_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 7, 52, 27, 498238, tzinfo=utc), verbose_name='expire_date'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish_date'),
        ),
    ]
