# Generated by Django 2.2.2 on 2020-04-27 00:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190712_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='prediction2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction2', to='quiz.Prediction'),
        ),
        migrations.AddField(
            model_name='choice',
            name='prediction3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction3', to='quiz.Prediction'),
        ),
        migrations.AddField(
            model_name='choice',
            name='prediction4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction4', to='quiz.Prediction'),
        ),
        migrations.AddField(
            model_name='choice',
            name='prediction5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction5', to='quiz.Prediction'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='prediction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction1', to='quiz.Prediction'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 0, 30, 40, 134717, tzinfo=utc), verbose_name='expire_date'),
        ),
    ]
